### ISSUE TITLE
Tree Groups not properly being displayed

### ISSUE THREAD

**Issue by michael-iglesias** [namespace-ee/react-calendar-timeline#162] opened 2017-08-25 14:56 UTC
<img width="882" alt="screen shot 2017-08-25 at 10 53 54 am" src="https://user-images.githubusercontent.com/4275784/29719379-cb6edfa4-8983-11e7-9595-e9666a1ee072.png">

Ex. When I select the 'Global IT' group it will then display all items that belong to that group under the 'Procurement' group instead of displaying the items directly under 'Global IT'

When toggling groups, the items that belong to the toggled group are not properly being nested immediately under the group title. I've copied & pasted the demo code from 'demo-tree-groups/index.js'.

```
// hide (filter) the groups that are closed, for the rest, patch their "title" and add some callbacks or padding
const newGroups = this.getTimelineGroups().groups.filter(g => g.root || this.state.openGroups[g.parent]).map(group => {
      return Object.assign({}, group, {
        title: group.root ? (
          <div onClick={() => this.toggleGroup(parseInt(group.id))} style={{cursor: 'pointer'}}>
            {this.state.openGroups[parseInt(group.id)] ? '[-]' : '[+]'} {group.title}
          </div>
        ) : (
          <div style={{paddingLeft: 20}}>
            {group.title}
          </div>
        )
      });
});
```

Has anyone run into this or have any recommendations on how to proceed?

**Comment by mariusandra** [comment] 2017-09-11 07:49
Hey, the groups are displayed in the order you create the newGroups array.

Looking at your code and taking a guess, probably your `this.getTimelineGroups().groups` returns an array where first you have all the root groups, followed by all the others.

Thus while you might be filtering them correctly, they are still shown in this order.

Try something like this:

```js
const allGroups = this.getTimelineGroups().groups
let visibleGroups

allGroups.filter(g => g.root).forEach(rootGroup => {
  visibleGroups.push(Object.assign({}, rootGroup, {
    title: (
      <div onClick={() => this.toggleGroup(parseInt(group.id))} style={{cursor: 'pointer'}}>
        {this.state.openGroups[parseInt(group.id)] ? '[-]' : '[+]'} {group.title}
      </div>
    )
  })

  // not sure how exactly the filter needs to be and if the rootGroup has an ID or not
  if (this.state.openGroups[rootGroup.id]) {
    allGroups.filter(g => g.parent === rootGroup.id).forEach(group => {
      visibleGroups.push(Object.assign({}, group, {
        title: (
          <div style={{paddingLeft: 20}}>
            {group.title}
          </div>
        )
      })
    })
  }
})
```

Hope this helps.

**Comment by mcMickJuice** [comment] 2018-01-18 03:32
@michael-iglesias did the above suggestion help?  If so, can you please close this issue?  If not, can you please provide a codesandbox example of this bug so that we can reproduce?

**Comment by mcMickJuice** [comment] 2018-01-20 17:21
The tree group example is provided to show the flexibility of the timeline and is not something that is explicitly built in to the library.  For triages sake im going to close this issue as its not a bug with the library, its one with the user code

**Closed by mcMickJuice** 2018-01-20 17:21 UTC
