### ISSUE TITLE
Container width in %

### ISSUE THREAD

**Issue by flyalex** [namespace-ee/react-calendar-timeline#39] opened 2016-07-24 21:11 UTC
Hi,

I am dividing my screen in to 2 parts. First contains timeline, second - other content. 
Second part has width param, first uses rest of space.

If second part has fixed size in pixels, timeline works great even when changing size of the browser.
But if second has width set in %, part of timeline disappear  accidentally (everything besides groups names).

Any Idea, how to solve it?
Thanks!

**Comment by ochervak** [comment] 2016-07-25 05:00
+1 that i have same problem.
i fixed it with calling `.resize()` method when layout changes. it it dirty hack, but it works in my case

BTW i use mobx

```
// Subscribe for layout changes
        this.dispose = observe(
            // Subscribe for my updates
            ui.filters.state[types.OVERVIEW_FILTER],
            (change) => {
                // If change is to open/close filter (which require re-painting)
                if (change.name === 'opened') {
                    // If we hide filter -> save initial width of timeline
                    if (!change.newValue) {
                        change.object.memorizedScrollWidth = this.refs.timeline.refs.scrollComponent.offsetWidth;
                        setTimeout(() => this.refs.timeline.resize(), 0);
                    // If we show filter -> restore saved initial width for timeline
                    } else {
                        this.refs.timeline.refs.scrollComponent.style.width = `${change.object.memorizedScrollWidth}px`;
                        setTimeout(() => this.refs.timeline.resize(), 0);
                    }
                    ui.showDebug('Trigger resize of overview');
                }
            });
    }
```

**Comment by mafzst** [comment] 2016-10-06 19:43
Any news here?

**Comment by mariusandra** [comment] 2017-06-28 11:01
Hey, while I couldn't reproduce the bug as you described, there is now support to detect changes to the width of the container itself. Here's [a demo](http://namespace.ee/react-calendar-timeline-docs/#/elementResize) where it works ([source](https://github.com/namespace-ee/react-calendar-timeline/blob/master/demo/app/demo-element-resize/index.js)). 

Closing this issue. Feel free to reopen if there are still issues.

**Closed by mariusandra** 2017-06-28 11:01 UTC
