### ISSUE TITLE
sidebarWidth={0} causes errors in React 0.14.4

### ISSUE THREAD

**Issue by ochervak** [namespace-ee/react-calendar-timeline#15] opened 2016-04-26 09:04 UTC
Issue related to #14 . 

When i used sidebarWidth={0} with latest `0.7.9` version and react 0.14.4, it cause:
```
logger.js:185Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).(…)invokeConsoleMethod @ logger.js:185
es6.promise.js:119Unhandled promise rejection TypeError: Cannot read property 'removeEventListener' of undefined(…)(anonymous function) @ es6.promise.js:119
4Header.js:61Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
Timeline.js:592Uncaught TypeError: Cannot read property 'scrollLeft' of undefinedReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:71
Header.js:61Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
```

**Comment by ochervak** [comment] 2016-04-26 09:05
Sorry to bother with issues...

**Comment by ochervak** [comment] 2016-04-26 09:07
![react-timeline-bug](https://cloud.githubusercontent.com/assets/13982649/14812804/7c6909c6-0ba7-11e6-9089-a8209426ce63.png)

**Comment by mariusandra** [comment] 2016-05-03 10:53
Hey, keep the issues coming when you find them! Unfortunately I haven't had time to look into this. The earliest I can promise to do so is this Thursday/Friday.

**Comment by ochervak** [comment] 2016-05-04 08:09
@mariusandra np bruh! i already ported my codebase to latest react, so it is not urgent for me

**Comment by mariusandra** [comment] 2016-05-05 12:28
Hey, sorry, I'm not able to reproduce this problem when using 0.14.4, including react-dom 0.14.4. And I can't find it with 0.14.8 either.

Any extra hints you can give me, or let's mark this as closed with the treatment "use react 15"?

**Comment by ochervak** [comment] 2016-05-05 12:30
@mariusandra lets go with `use react 15` i think..

**Comment by mariusandra** [comment] 2016-05-05 12:31
Great choice! 👍 

Closing issue. :)

**Closed by mariusandra** 2016-05-05 12:31 UTC
