### ISSUE TITLE
Browser Zoom causes row height mismatch problem

### ISSUE THREAD

**Issue by devictokai** [namespace-ee/react-calendar-timeline#265] opened 2018-04-06 01:07 UTC
Looking at the test case at [codesandbox.io](https://codesandbox.io/s/qlj6qvjrnw) , with Chrome or Firexfox with the browsers zoom level set to 100%, the table looks fine.

However when changing the zoom level to 110% in Chrome, the row height of the calendar item titles on the left, no longer matches the row height of the calendar items on the right. Can be seen if looking at the last row at bottom of the table in the linked codesandbox.

![image](https://user-images.githubusercontent.com/38119362/38398904-f8525e0c-3981-11e8-956e-472afa9e134b.png)

For Firefox, the misalignment becomes increasingly worse with increased zoom level.

![image](https://user-images.githubusercontent.com/38119362/38398935-25b33b32-3982-11e8-8c2d-6432edac6f87.png)

Additionally, the bug also seems to occur on some machines with high dpi displays, even with the zoom level set to 100%.  (Whereas, another zoom level, such as 130%, might work)

**Comment by devictokai** [comment] 2018-04-10 06:09
As a FYI, one of our developers is currently using the following css snippet as a workaround.
I thought I'd add it here as a hint to in what area the problem might be in.

```css
/* for browser zoom bug, search item part */
.react-calendar-timeline .rct-sidebar .rct-sidebar-row {
   border-bottom-width: 0 !important;
   padding-bottom: 1px !important;
}
.react-calendar-timeline .rct-sidebar .rct-sidebar-row .rct-sidebar-row-odd {
   border-bottom-width: 0 !important;
   padding-bottom: 1px !important;
}
/* for browser zoom bug, calender part */
.react-calendar-timeline .rct-horizontal-lines .rct-hl-odd {
   border-bottom-color: #f2f2f2 !important; }
.react-calendar-timeline .rct-horizontal-lines .rct-hl-even, .react-calendar-timeline.rct-horizontal-lines .rct-hl-odd {
  border-bottom-color: white;
 }
```

**Comment by mcMickJuice** [comment] 2018-05-11 11:08
Hello, I can't reproduce this (Mac, using Chrome 66.0.3359.139) and if you have a workaround I'm going to close this.

Also this might be due to your adding padding to rows and sidebar rows.  That will likely mess things up in the timeline as it's positioning does not take CSS into account.  So...you might have a bad time when you do this

**Closed by mcMickJuice** 2018-05-11 11:08 UTC
Labels: bug

**Comment by devictokai** [comment] 2018-05-14 00:51
Hello, thanks for looking into this. 
First of all, I don't have any problem with you closing this, as we do have a workaround.

But just as an FYI, the problem still occurs on Mac, Chrome 66.0.3359.139 (official build) (64 bit). and can be reproduced by the following steps.

1. Open Chrome in maximized, but not full-screen window mode.
2. Set browser zoom to 110%
3. Go to https://github.com/namespace-ee/react-calendar-timeline/tree/master/examples.
4. Click the "Basic Usage" "Example Codesandbox" link.
5. Check the alignment of row 3 from the bottom.

Result: Line is offset by 1 or 2 pixels.  (It is not as pronounced as it used to be. I don't know if this is due to updates to the master branch, or because of different HW/OS combo)

I am not the developer working on this, so I am not sure exactly what they did in terms of padding etc. but I will forward your advice.

I note; however, that if I "un-dock" the right-side browser result in codesandbox.io , i.e. clicking the "open in new window" link, the problem disappears. So maybe the problem is somehow related to the minimum width or something.

**Comment by mcMickJuice** [comment] 2018-05-14 01:03
I've encountered some weirdness with codesandbox, both with alignment and other really strange issues.

**Comment by devictokai** [comment] 2018-05-14 01:07
Yes, but our dev is seeing it on his live product as well. However, this all made me go back and check Firefox on windows (where the problem is still bad, with tens of pixels in misalignment), and also with FF on windows. On code sandbox once again, the problem goes away when undocking the output-frame on.  So I think this problem might be related to the width of the parent container or something.

Once again, thanks for looking into this. I will forward your comments regarding padding and the new info on possible relation to parent-window size to them, and I think that will be all that they need to solve their problems.

**Comment by joncar** [comment] 2018-07-15 01:19
I see the problem but I'm not sure of the right solution.

Firefox is rendering the border of the left elements with at least 1 (screen) px. The left elements have their top automatically calculated via HTML layout and so their top/height is based on a 1 (screen) px border, but the right elements have their top set explicitly in their style based on JavaScript calculations which I assume is using a fractional (screen) px border height in its calculation.

You can see this effect happening in Firefox's F12 debugger. Select one of the CSS elements with a border and watch the CSS Layout view. When the Layout view shows the border as a whole number then everything lines up, but if you zoom in or out so that the Layout has a fractional value then this mismatch appears.

Perhaps both sides should use JavaScript calculated tops?
