### ISSUE TITLE
Move multiple items

### ISSUE THREAD

**Issue by maxaggedon** [namespace-ee/react-calendar-timeline#315] opened 2018-05-23 07:59 UTC
This is a question / feature request.

Is it possible to move multiple items in one drag?

I know its possible to select multiple items, but this does not make it possible to move them together. Is it possible, or has it already been discussed? I couldn't find anything on the subject.

**Comment by vasdee** [comment] 2018-05-24 00:48
There is a current PR for this open for discussion. Now would be a perfect time to jump in with your thoughts on it

https://github.com/namespace-ee/react-calendar-timeline/pull/314

**Comment by mcMickJuice** [comment] 2018-05-24 00:52
what @vasdee said :)

duplicate of https://github.com/namespace-ee/react-calendar-timeline/issues/215

**Closed by mcMickJuice** 2018-05-24 00:52 UTC

**Comment by maxaggedon** [comment] 2018-06-14 08:21
@vasdee @mcMickJuice I looked at the PR discussion, and my use case is much simpler than what you are discussing. I have only one item per group and items cannot change groups (kind of like a gantt chart). So I have no insight on "squashing" or collision. I'll let you guys decide what's best on those matters!
