### ISSUE TITLE
Question: Show range of specified hours

### ISSUE THREAD

**Issue by blz-ea** [namespace-ee/react-calendar-timeline#626] opened 2019-07-20 00:12 UTC
Hey guys, thank you very much for such a cool component.

Is there a way to show a timeline (day timeline to be specific) from a specific time e.g. 08:00 - 18:00 but keep other behavior as it is. 
Basically: if a user is in day timeline his viewport of the timeline should be from 08:00 till 18:00

**Comment by otang** [comment] 2019-11-29 07:20
I'm also looking for similar behaviour. I'd like to show a week view, but only show working hours (9-5) for each day. I'm playing around with `intervalRenderer` to see if I can skip intervals, not sure how well it will work but I'll let you know what I find.

**Comment by Ilaiwi** [comment] 2020-02-17 12:38
@blz-ea @otang this is a duplicate of #685. We are still not planing to support this unless someone is going to contribute it.

**Closed by Ilaiwi** 2020-02-17 12:38 UTC

**Comment by THPubs** [comment] 2020-03-02 12:19
@otang Any luck with `intervalRenderer`?
