### ISSUE TITLE
Scrolling automatically in some screen size when scale the browser

### ISSUE THREAD

**Issue by cw196** [namespace-ee/react-calendar-timeline#528] opened 2019-03-01 01:09 UTC
**Describe the bug**
When scaling the browser and in some certain screen size, the calendar is automatically scrolling back infinitely.

**To Reproduce**

1. Go to scale browser to 75% for example
2. resize screen to certain size, say 1940 * 1117.330
3. the calendar is scrolling back continuesly.

**Expected behavior**
Calendar should not move at all

**Screenshots**

**Library Version**
0.21.0

**Desktop (please complete the following information):**

* OS: MacOs
* Browser: chrome
* VersioN 72.0.3626.119 (Official Build) (64-bit)

**Comment by Ilaiwi** [comment] 2019-03-06 09:24
@cw196  I couldn't reproduce this on MacOS. are you using windows? are you using codesandbox? and please use the latest version of the library.

**Comment by cw196** [comment] 2019-05-06 03:07
@Ilaiwi

**Comment by cw196** [comment] 2019-05-06 03:39
@Ilaiwi Please have a look at 

https://codesandbox.io/s/9j1lmj1k8r
![refreshPageTimelineExample](https://user-images.githubusercontent.com/9029946/57205738-ba5fad00-7014-11e9-864f-15941cce434b.gif)

I'm using MacOS. And open the `codesandbox` in Chrome with 80% scale of your browser. 
Then on some level, you can notice the items are getting updated continuously. (If it doesn't act like described, please resize the `codesandbox`'s browser size. It will appear easily).

The reason for this issue is because that `visibleTimeStart` param passed back from `onTimeChange` is different from the `visibleTimeStart` param that passed to < Timeline /> on the none-100% browser scale in some case.

**Comment by Ilaiwi** [comment] 2019-06-09 14:17
released in 0.25.2

**Closed by Ilaiwi** 2019-06-09 14:17 UTC
Labels: cant repro, pending-release
