### ISSUE TITLE
Module parse failed: You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by baconprestosh** [namespace-ee/react-calendar-timeline#202] opened 2018-01-02 14:08 UTC
I am getting the following error: 

ERROR in ./~/react-calendar-timeline/lib/lib/Timeline.css
Module parse failed: /Users/jasonprestosh/response_project/node_modules/react-calendar-timeline/lib/lib/Timeline.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .react-calendar-timeline * {
|   box-sizing: border-box; }
|
 @ ./~/react-calendar-timeline/lib/lib/Timeline.js 24:0-25
 @ ./~/react-calendar-timeline/lib/index.js
 @ ./react/src/containers/ReactTimelineContainer.js
 @ ./react/src/containers/DashboardContainer.js
 @ ./react/src/App.js
 @ ./react/src/main.js

I previously had the same parsing error telling me I needed an appropriate loader for a different file, which was corrected by adding /lib to the end of "import Timeline from 'react-calendar-timeline';", so I'm not entirely sure the problem is with needing a loader.

**Comment by mcMickJuice** [comment] 2018-01-13 04:52
duplicate of https://github.com/namespace-ee/react-calendar-timeline/issues/195

**Closed by mcMickJuice** 2018-01-13 04:52 UTC
Labels: duplicate
