### ISSUE TITLE
Request: Groups drag and drop sorting

### ISSUE THREAD

**Issue by uffou** [namespace-ee/react-calendar-timeline#246] opened 2018-02-18 14:53 UTC
The ability to click and drag on an entire group in the left or right sidebar and drop it under/over other groups +  drop callback so that you can trigger business logic. If the entire row drags it's going to be a bonus. Something similar to [sortable HOC](http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/basic-usage?_k=g9w1px) maybe

**Comment by mcMickJuice** [comment] 2018-02-18 15:11
I wonder if this functionality could be achieved using [groupRenderer](https://github.com/namespace-ee/react-calendar-timeline#grouprenderer) and the library you referenced.

User code could respond to the drop event and restructure the elements passed into the groups prop.  Either way, I think this kind of functionality should not be part of the core library but would instead be a "recipe" that would be listed [here](https://github.com/namespace-ee/react-calendar-timeline/tree/master/examples).  If it's not achievable due to the implementation of this library, then we look at the implementation to allow for customization like this.  Thoughts?

**Comment by mcMickJuice** [comment] 2018-03-02 01:20
I'm going to close this as I don't believe this is within the purview of this library.

**Closed by mcMickJuice** 2018-03-02 01:20 UTC
Labels: feature-request

**Comment by fpaupier** [comment] 2020-12-30 08:06
@uffou - Did you manage to get this DnD behavior? If so, would you be so kind as to share a reproducible example of it?
