### ISSUE TITLE
When CustomMarker date prop changes marker doesn't move on the timeline

### ISSUE THREAD

**Issue by kevinmanncito** [namespace-ee/react-calendar-timeline#421] opened 2018-09-14 20:05 UTC
**Describe the bug**
Changing the `date` prop passed into a `CustomMarker` component doesn't update on the timeline.

**To Reproduce**
Code sandbox: https://codesandbox.io/s/q9x8zp0qp9

Just enter in numbers in the text field above the time and you can see that the state is updating but the marker on the timeline doesn't move.

~Run the `marker-change-bug` branch on my [fork](https://github.com/kevinmanncito/react-calendar-timeline/tree/marker-change-bug).~

~Go to the main demo and add numbers in the text field I added and you can see that the state of the marker date is changing but the timeline isn't updating.~

**Expected behavior**
The timeline marker should update if the date being passed into the timeline marker changes.

**Screenshots**
![marker_bug](https://user-images.githubusercontent.com/2521298/45572422-753cff80-b826-11e8-8daa-fe36fe3a2d01.gif)

**Library Version**
0.19.0

**Desktop (please complete the following information):**

* OS: macOS 10.13.6
* Browser: Chrome 69.0.3497.92

**Smartphone (please complete the following information):**
N/A

**Additional context**
Hopefully I'm not missing something obvious but I've been looking at this for a while and it feels like it should be updating. Looks like it could be a bug with the markers provider/consumer logic. Not sure how to fix it tho. Any ideas? Thanks!

**Comment by Ilaiwi** [comment] 2018-09-14 20:08
Hi, @kevinmanncito could you please replicate this in https://codesandbox.io/s/zr5r289rm4
It will be easier for all of us helping you here

**Comment by kevinmanncito** [comment] 2018-09-14 20:18
Updated issue with a code sandbox demo: https://codesandbox.io/s/q9x8zp0qp9

**Comment by Ilaiwi** [comment] 2018-09-14 20:54
@kevinmanncito yes this is a bug. The problem is that the `CustomMarker` inside `src/lib/markers/implementation/CustomMarkers` is not getting the new date. So there is a quick hack fix that will work just fine implemented [here](https://codesandbox.io/s/6x22l3npkz)
I would appreciate if you went and fixed submitted a PR and fixed this issue 🥇

**Comment by kevinmanncito** [comment] 2018-09-15 04:53
You got it: https://github.com/namespace-ee/react-calendar-timeline/pull/422 let me know if you can see a better way of fixing this

**Comment by Ilaiwi** [comment] 2018-10-13 17:14
released in 0.20.0

**Closed by Ilaiwi** 2018-10-13 17:14 UTC
Labels: bug, help wanted, pending-release
