### ISSUE TITLE
Option to edit the date header label?

### ISSUE THREAD

**Issue by yftachman** [namespace-ee/react-calendar-timeline#337] opened 2018-06-20 17:20 UTC
Hey, I'd like to edit the way the date at the top is styled (both text and look),
also for the header label group (red part on top).

**Describe the solution you'd like**
Let me pass a method to the Timeline object, if present gives for each column the date it represents, maybe format (as in if its days, months etc...) and expect a return value of jsx object. 

**Describe alternatives you've considered**
Only other way to do it is set headerLabelHeight to 0, and add elements of my own in a hacky way to.

**Comment by mcMickJuice** [comment] 2018-06-20 17:30
Duplicate of https://github.com/namespace-ee/react-calendar-timeline/issues/329

**Comment by mcMickJuice** [comment] 2018-06-20 17:30
hi @yftachman can you please bring this request over to the referenced issue above?

**Closed by mcMickJuice** 2018-06-20 17:30 UTC

**Comment by yftachman** [comment] 2018-06-21 08:05
Yeah sure,
however in my opinion that issue is a sub-case of this issue, but whatever.
