### ISSUE TITLE
Possibility to fire a drag-end event

### ISSUE THREAD

**Issue by MocanuMarius** [namespace-ee/react-calendar-timeline#169] opened 2017-10-02 11:00 UTC
I'm using the timeline item onClick event in order to fire-up a modal, but my problem is that after i dismiss the modal, the "drag state" inside the calendar is still on /turned on and the UX is pretty bad since it starts dragging by itself to wherever i click to dismiss the modal. I would like a mechanism to say "please disengage dragging mode", if it is feasable.

**Comment by MocanuMarius** [comment] 2017-10-03 12:58
Solved this in another way:

- Disabled all kind of selects and clicks from the main calendar timeline props.
- Added click handler in each of item's props.

Works as intended, select is not blocking anything anymore, but if you want to also be able to move things ....not sure ... but since i have a modal that's not a problem.

**Comment by mcMickJuice** [comment] 2018-01-13 04:41
Duplicate of https://github.com/namespace-ee/react-calendar-timeline/issues/182

**Closed by mcMickJuice** 2018-01-13 04:41 UTC
Labels: duplicate
