### ISSUE TITLE
onCanvasClick is not triggered when position changes

### ISSUE THREAD

**Issue by hotyhuang** [namespace-ee/react-calendar-timeline#298] opened 2018-05-03 04:11 UTC
Hi,
Another question, I am injecting this `calendar timeline` in the page in a certain position. But the content above it might get cleared bcs of user action, like:
```
<content />         
<Timeline />          --->             <Timeline />
```
In this case, the `onCanvasClick` is not working properly. But if I put the content back, this `onCanvasClick` starts to work again.

I guess this happen bcs of the html canvas behavior. Another scenario to test is, if you minimize your browser height, the canvas will also lose track.

So is there any workaround method?

**Comment by mcMickJuice** [comment] 2018-05-03 14:29
hi @hotyhuang can you please provide a codesandbox link that reproduces this issue?  Just fork one of the [examples](https://github.com/namespace-ee/react-calendar-timeline/tree/master/examples)

**Comment by mcMickJuice** [comment] 2018-05-03 17:58
👍 excellent thank you

**Comment by mcMickJuice** [comment] 2018-05-04 14:54
Looks like this is fixed in beta:

https://codesandbox.io/s/jvy8wkvrvy

Can you confirm @hotyhuang ?  If so, I'll keep this open until that is released

**Comment by mcMickJuice** [comment] 2018-05-04 14:57
related to https://github.com/namespace-ee/react-calendar-timeline/issues/159

**Comment by hotyhuang** [comment] 2018-05-04 17:58
@mcMickJuice I think the click is not so accurate with sandbox itself. But ye, the actual problem is resolved in this beta.
Btw, when are you guys planning to do the next release?

**Comment by mcMickJuice** [comment] 2018-05-04 18:27
Very soon. I'm waiting on a response from someone regarding a bug they encountered this morning.  Hopefully this weekend.

**Comment by mcMickJuice** [comment] 2018-05-04 22:11
https://github.com/namespace-ee/react-calendar-timeline/issues/296

**Closed by mcMickJuice** 2018-05-04 22:11 UTC
Labels: bug, pending-release
